server:
  servlet:
    context-path: /api/v1

payment:
  security:
    iam:
      enabled: true
      issuer: "https://your-iam-provider.com"
      audience: "payment-service"
      #jwks-uri: "https://your-iam-provider.com/.well-known/jwks.json"
      # OR use mock for testing
      jwks-uri: "http://localhost:8080/api/v1/.well-known/jwks.json"
      mock-jwks-enabled: true
      token-expiration-ms: 3600000
      jwks-cache-duration-ms: 3600000
      validate-issuer: true
      validate-audience: true
      jwks-connect-timeout-ms: 5000
      jwks-read-timeout-ms: 5000

spring:
  application:
    name: sample-payments-service
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:mydb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    tryItOutEnabled: true
  show-actuator: false

logging:
  external:
    body-enabled: false